/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "game_constants.h"

namespace pulsegame {

const gameConstants g_game_constants;

gameConstants::gameConstants() {
}

} // namespace

