/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef game_CONSTANTS_H
#define game_CONSTANTS_H

#include "game_types.h"

namespace pulsegame {

class gameConstants {
 public:
  gameConstants();

};

extern const gameConstants g_game_constants;

} // namespace

#endif
